@startuml
'https://plantuml.com/sequence-diagram

autonumber

actor "Administrator" as OE
activate OE

OE -> ":System" : starts new parameter category
activate ":System"
":System" --> OE : request data (code, description, nhsID)
deactivate ":System"

OE -> ":System" : types requested data
activate ":System"
":System" --> OE : show the data and requests a confirmation
deactivate ":System"

OE -> ":System" : confirms the data
activate ":System"
":System" --> OE : informs operation success
deactivate ":System"


deactivate OE

@enduml